# Metadata
sonar.projectKey=buildmarket-backend
sonar.projectName=BuildMarket Backend
sonar.projectVersion=1.0

# Paths
sonar.sources=server/src
sonar.exclusions=**/node_modules/**, **/tests/**, **/coverage/**
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
