apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: buildmarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: imemayachi/buildmarket-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/buildmarket"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: buildmarket
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
